### ISSUE TITLE
No decoder surfaces left, cannot allocate memory

### ISSUE THREAD

**Issue by Joshua-Noakes1** [Joshua-Noakes1/Teardown-nvenc#3]
"Doesnt work, it constantly says No decoder surfaces left, cannot allocate memory

output is first frame and sounds. gpu is 3070. pls help" - Odd_Ad9780

https://www.reddit.com/r/TeardownGame/comments/t5wvgx/comment/hzaz7j0/?utm_source=share&utm_medium=web2x&context=3

**Comment by Joshua-Noakes1** [comment]
fixed by adding ```-extra_hw_frames 2``` before file input - https://stackoverflow.com/a/68061732

**Comment by Joshua-Noakes1** [comment]
Didn't fix it apparently

**Comment by sirbnjmn** [comment]
Screenshot of issue occurring 
![image](https://user-images.githubusercontent.com/67805439/156847156-8a319d84-1f60-496e-ae7c-bc197056a518.png)

**Comment by Joshua-Noakes1** [comment]
FFmpeg needs to have NVENC support at build
