### ISSUE TITLE
FFMPEG.exe named wrong.

### ISSUE THREAD

**Issue by ben0x00** [Joshua-Noakes1/Teardown-nvenc#4]
When running the script , it appears to be searching for ffmpeg.exe, rather than "ffmpeg-4.2.3-NVENC.exe" which is included with the download. I assume the filename just needs to be changed.

**Comment by Joshua-Noakes1** [comment]
Yeah the script looks for “ffmpeg.exe” just renaming it should work for the ffmpeg in the repo and any ffmpeg you can find or compile.
